package com.mesaflow.client.core.designsystem

import androidx.compose.ui.graphics.Color

/*
 * Paleta MesaFlow generada desde el color semilla de marca #00696D (teal)
 * con terciario terracota (#9A4520) como acento cálido para comida.
 * Valores tonales siguiendo el algoritmo de Material Theme Builder.
 */

// --- Light ---
internal val PrimaryLight = Color(0xFF00696D)
internal val OnPrimaryLight = Color(0xFFFFFFFF)
internal val PrimaryContainerLight = Color(0xFF9CF1F5)
internal val OnPrimaryContainerLight = Color(0xFF002021)
internal val SecondaryLight = Color(0xFF4A6365)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val SecondaryContainerLight = Color(0xFFCCE8E9)
internal val OnSecondaryContainerLight = Color(0xFF051F21)
internal val TertiaryLight = Color(0xFF9A4520)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val TertiaryContainerLight = Color(0xFFFFDBCD)
internal val OnTertiaryContainerLight = Color(0xFF380D00)
internal val ErrorLight = Color(0xFFBA1A1A)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val ErrorContainerLight = Color(0xFFFFDAD6)
internal val OnErrorContainerLight = Color(0xFF410002)
internal val BackgroundLight = Color(0xFFFAFDFC)
internal val OnBackgroundLight = Color(0xFF191C1C)
internal val SurfaceLight = Color(0xFFFAFDFC)
internal val OnSurfaceLight = Color(0xFF191C1C)
internal val SurfaceVariantLight = Color(0xFFDAE4E5)
internal val OnSurfaceVariantLight = Color(0xFF3F4849)
internal val OutlineLight = Color(0xFF6F797A)
internal val OutlineVariantLight = Color(0xFFBEC8C9)
internal val InverseSurfaceLight = Color(0xFF2D3131)
internal val InverseOnSurfaceLight = Color(0xFFEFF1F1)
internal val InversePrimaryLight = Color(0xFF80D4D9)
internal val SurfaceDimLight = Color(0xFFDADDDD)
internal val SurfaceBrightLight = Color(0xFFFAFDFC)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFF4F7F7)
internal val SurfaceContainerLight = Color(0xFFEEF1F1)
internal val SurfaceContainerHighLight = Color(0xFFE8EBEB)
internal val SurfaceContainerHighestLight = Color(0xFFE2E5E5)

// --- Dark ---
internal val PrimaryDark = Color(0xFF80D4D9)
internal val OnPrimaryDark = Color(0xFF003739)
internal val PrimaryContainerDark = Color(0xFF004F52)
internal val OnPrimaryContainerDark = Color(0xFF9CF1F5)
internal val SecondaryDark = Color(0xFFB1CBCD)
internal val OnSecondaryDark = Color(0xFF1B3436)
internal val SecondaryContainerDark = Color(0xFF324B4D)
internal val OnSecondaryContainerDark = Color(0xFFCCE8E9)
internal val TertiaryDark = Color(0xFFFFB598)
internal val OnTertiaryDark = Color(0xFF5B1B00)
internal val TertiaryContainerDark = Color(0xFF7A2E09)
internal val OnTertiaryContainerDark = Color(0xFFFFDBCD)
internal val ErrorDark = Color(0xFFFFB4AB)
internal val OnErrorDark = Color(0xFF690005)
internal val ErrorContainerDark = Color(0xFF93000A)
internal val OnErrorContainerDark = Color(0xFFFFDAD6)
internal val BackgroundDark = Color(0xFF111414)
internal val OnBackgroundDark = Color(0xFFE0E3E3)
internal val SurfaceDark = Color(0xFF111414)
internal val OnSurfaceDark = Color(0xFFE0E3E3)
internal val SurfaceVariantDark = Color(0xFF3F4849)
internal val OnSurfaceVariantDark = Color(0xFFBEC8C9)
internal val OutlineDark = Color(0xFF899393)
internal val OutlineVariantDark = Color(0xFF3F4849)
internal val InverseSurfaceDark = Color(0xFFE0E3E3)
internal val InverseOnSurfaceDark = Color(0xFF2D3131)
internal val InversePrimaryDark = Color(0xFF00696D)
internal val SurfaceDimDark = Color(0xFF111414)
internal val SurfaceBrightDark = Color(0xFF373A3B)
internal val SurfaceContainerLowestDark = Color(0xFF0B0F0F)
internal val SurfaceContainerLowDark = Color(0xFF191C1C)
internal val SurfaceContainerDark = Color(0xFF1D2021)
internal val SurfaceContainerHighDark = Color(0xFF272B2B)
internal val SurfaceContainerHighestDark = Color(0xFF323536)
